{% set python_min = "3.11.0" %}
{% set name = "fractal-server" %}
{% set version = "2.18.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fractal_server-{{ version }}.tar.gz
  sha256: 7555cde45a8795170c30ecffc0fb2a896edb42fcab3c1b3efa0922f5e8cba295

build:
  entry_points:
    - fractalctl = fractal_server.__main__:run
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - tomli-w <1.3.0,>=1.2.0
    - python >={{ python_min }},<3.15
    - fastapi >=0.120.0,<0.121.0
    - sqlmodel ==0.0.27
    - sqlalchemy >=2.0.23,<2.1
    - fastapi-users >=15,<16
    - alembic >=1.13.1,<2.0.0
    - uvicorn >=0.38.0,<0.39.0
    - uvicorn-worker ==0.4.0
    - pydantic >=2.12.0,<2.13.0
    - pydantic-settings ==2.11.0
    - packaging >=25.0.0,<26.0.0
    - fabric >=3.2.2,<3.3.0
    - gunicorn >=23.0,<24.0
    - psycopg >=3.1.0,<4.0.0

test:
  imports:
    - fractal_server
  commands:
    - pip check
    - fractalctl --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/fractal-analytics-platform/fractal-server
  summary: Backend component of the Fractal analytics platform
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ychiucco
    - jluethi
    - mfranzon
    - tcompa
