{% set python_min = "3.11.0" %}
{% set name = "fractal-server" %}
{% set version = "2.16.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fractal_server-{{ version }}.tar.gz
  sha256: 7527ac602a0462084732cf71b1dd4dedc67d03699c7a9b313cad1f91600324d9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - fractalctl = fractal_server.__main__:run
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - tomli-w >=1.2.0,<1.3.0
    - httpx
    - invoke
    - paramiko
    - python >={{ python_min }},<4.0.0
    - python-dotenv >=1.1.0,<1.2.0
    - fastapi >=0.118.0,<0.119.0
    - sqlmodel ==0.0.27
    - sqlalchemy >=2.0.23,<2.1
    - fastapi-users >=14,<15
    - alembic >=1.13.1,<2.0.0
    - uvicorn >=0.37.0,<0.38.0
    - uvicorn-worker ==0.4.0
    - pydantic >=2.12.0,<2.13.0
    - pydantic-settings ==2.11.0
    - packaging >=25.0.0,<26.0.0
    - fabric >=3.2.2,<3.3.0
    - gunicorn >=23.0,<24.0
    - psycopg >=3.1.0,<4.0.0
    - cryptography >=46.0.0,<47.0.0

test:
  imports:
    - fractal_server
  commands:
    - pip check
    - fractalctl --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/fractal-analytics-platform/fractal-server
  summary: Backend component of the Fractal analytics platform
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ychiucco
    - jluethi
    - mfranzon
    - tcompa
