{% set name = "fractal-server" %}
{% set version = "1.3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fractal_server-{{ version }}.tar.gz
  sha256: 0128c498a886b5ab1effc2a8a82af254fba47c12ef7a8133f95c633250fba80c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - fractalctl = fractal_server.__main__:run
  number: 0

requirements:
  host:
    - python >=3.9,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.9.0,<4.0.0
    - python-dotenv >=0.20.0,<0.21.0
    - fastapi >=0.95.0,<0.96.0
    - sqlmodel >=0.0.8,<0.0.9
    - aiosqlite >=0.17.0,<0.18.0
    - fastapi-users >=10.1.0,<11.0.0
    - alembic >=1.9.1,<2.0.0
    - uvicorn >=0.20.0,<0.21.0
    - sqlalchemy >=1.4.0,<2.0.0
    - sqlalchemy-utils >=0.38.3,<0.39.0
    - greenlet *
    - pydantic >=1.10.8,<2
  run_constrained:
    - clusterfutures >=0.5.0,<0.6.0
    - cloudpickle >=2.2.1<2.3.0
    - asyncpg >=0.27.0,<0.28.0
    - psycopg2 >=2.9.5,<3.0.0
    - gunicorn >=20.1.0,<21.0.0

test:
  imports:
    - fractal_server
  commands:
    - pip check
    - fractalctl --help
  requires:
    - pip

about:
  home: https://github.com/fractal-analytics-platform/fractal-server
  summary: Server component of the Fractal analytics platform
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tcompa
